Squashing a few usability bugs..

diff --git a/lib/githose/clone b/lib/githose/clone
--- a/lib/githose/clone
+++ b/lib/githose/clone
@@ -12,7 +12,10 @@
 
 [ -d '../inc' ] && cd .. || ( [ -d '../../inc' ] && cd ../.. )
 
-(source etc/githose.conf && source inc/inits && source inc/colors && source inc/funcs) || exit -- $BASH_LINENO
+source etc/githose.conf
+source inc/inits
+source inc/colors
+source inc/funcs
 
 ### (o) DONUT ED IT ANYFING BLOW THIS (o) ###
 
@@ -41,25 +44,33 @@ if [[ $gitUser =~ ^(http|git)[s]:[/]+ ]]
 fi
 
 function errx_show() {
-  echo -n "${yellowb}$1${whitef}${boldon}:${boldoff}${reset}${yellowb} " 
+  which perror 2>/dev/null
 
-  perror -s -- $2
+  if [ $? -ne 0 ]
+    then echo -n "${yellowb}$1${whitef}${boldon}:${boldoff}${reset}${yellowb} " 
 
-  echo "$reset"
+    perror -s -- $2
+
+    echo "$reset"
+  fi
 
   return 0
 }
 
 function errx_exit() {
-  readonly reposPath=$(realpath $3)
+  which perror 2>/dev/null
 
-  echo -n "${redb}$1${whitef}${boldon}:${boldoff}${reset}${redb} " 
+  if [ $? -ne 0 ]
+    then readonly reposPath=$(realpath $3)
 
-  [ "$reposPath" ] && echo -n "$reposPath "
+    echo -n "${redb}$1${whitef}${boldon}:${boldoff}${reset}${redb} " 
 
-  perror -v -- $2
+    [ "$reposPath" ] && echo -n "$reposPath "
 
-  echo -n "$reset"
+    perror -v -- $2
+
+    echo -n "$reset"
+  fi
 
   exit -- $2
 }
@@ -69,7 +80,7 @@ if [ $singleRepo -ne 0 ]
 
   echo -ne "${purplef}$0${whitef}${boldon}:${boldoff} ${cyanf}Handling URI Style Input as Single Git Repository${whitef}${boldon}:${boldoff} ${reset}${invon}${gitUser}${reset}\n${whitef}${italicson}" 
 
-  git clone $gitUser
+  git clone $gitUser > /dev/null 2>&1
 
   if [ $? ]
     then declare -i -r errCode=$? 
@@ -92,7 +103,7 @@ if [ ! -d $GITAA_PATH_CLONE ]
   [ $? -ne 0 ] && errx_show 'mkdir' "$?" $GITAA_PATH_CLONE
 fi
 
-chmod $GITAA_MODE_CDIRS $GITAA_PATH_CLONE |&> /dev/null
+chmod $GITAA_MODE_DIRS $GITAA_PATH_CLONE |&> /dev/null
 
 [ $? -ne 0 ] && errx_show 'chmod' "$?"
 
@@ -105,7 +116,7 @@ if [ ! -d $gitUser ]
 
   [ $? -ne 0 ] && errx_exit 'mkdir' $? $gitUser
 
-  chmod $GITAA_MODE_CDIRS $gitUser |&> /dev/null
+  chmod $GITAA_MODE_DIRS $gitUser |&> /dev/null
 
   [ $? -ne 0 ] && errx_show 'chmod' "$?"
 fi
@@ -129,7 +140,7 @@ while true
     then 
     echo "${purplef}$0${reset}${whitef}${boldon}:${boldoff} ${yellowf}No output received from GitHub API!${reset}"
     echo -n "${purplef}$0${reset}${whitef}${boldon}:${boldoff} " 
-    echo "${redf}$(cat $errorFile | tr '*' '#' | tr '\n' ' ' | sed -r 's![#]!..!g')${reset}"
+    echo "${redf}$(cat $errorFile | tr '*' '#' | tr '\n' ' ' | sed 's![#]!..!g')${reset}"
 
     rm -f -- "$errorFile"
 
@@ -142,7 +153,7 @@ while true
     exit 3 
   fi
 
-  export GITHUB_REPO_URLS=$(echo "$outputStr" | grep '"html_url": "' | grep -- "/${gitUser}/" | cut -d \" -f4 | sed 's!^git://!https://!g' | sed "s!https://github.com/${gitUser}/!!g" | sed -r 's![/]+!!gi' | tr '\012' ' ' | sed -r 's![ ]*$!!')
+  export GITHUB_REPO_URLS=$(echo "$outputStr" | grep '"html_url": "' | grep -- "/${gitUser}/" | cut -d \" -f4 | sed 's!^git://!https://!g' | sed "s!https://github.com/${gitUser}/!!g" | sed 's![/]+!!g' | tr '\012' ' ' | sed 's![ ]*$!!')
 
   if [ ! "$GITHUB_REPO_URLS" ] 
     then echo "${purplef}$0${whitef}${boldon}:${boldoff} ${yellowf}Received output from GitHub API, but no repository references?${reset}"
@@ -151,7 +162,7 @@ while true
 
     exit 4
   else
-    echo -e "${greenf}${ulon}${GITHUB_REPO_URLS}${reset}\n" | sed -r "s! !${reset} ${greenf}${ulon}!g"
+    echo -e "${greenf}${ulon}${GITHUB_REPO_URLS}${reset}\n" | sed "s! !${reset} ${greenf}${ulon}!g"
   fi
 
   declare -i aflag=$false
@@ -175,7 +186,7 @@ while true
   if [ ! $? ]
     then echo -n "${whitef}${italicson}" 
 
-    parallel --fg -j${GITHOSE_NUM_JOBS} git clone "https://github.com/${gitUser}/{1}" ::: $GITHUB_REPO_URLS
+    parallel --fg -j${GITHOSE_NUM_JOBS} git clone "https://github.com/${gitUser}/{1}" > /dev/null 2>&1 ::: $GITHUB_REPO_URLS
 
     [ $successVal -eq 0 ] && [ $? -eq 0 ] && successVal=1
   else
@@ -191,12 +202,12 @@ while true
 
         echo $one
         
-        git clone -- "https://github.com/${gitUser}/${one}" &
+        nice git clone -- "https://github.com/${gitUser}/${one}" > /dev/null 2>&1 &
       fi
     done
 
     for two in `seq 1 $countChocula`
-      do wait %${two} |&> /dev/null
+      do wait %${two} 2> /dev/null
 
       [ $successVal -eq 0 ] && [ $? -eq 0 ] && successVal=1
     done
